
import { Translations, Language } from './types';

export const TRANSLATIONS: Record<Language, Translations> = {
  en: {
    title: 'QR Pro',
    subtitle: 'Professional QR Code Studio',
    url: 'URL',
    text: 'Text',
    whatsapp: 'WhatsApp',
    email: 'Email',
    wifi: 'Wi-Fi',
    generate: 'Generate QR Code',
    downloadPng: 'Download PNG',
    downloadSvg: 'Download SVG',
    copy: 'Copy to Clipboard',
    size: 'Size',
    color: 'Foreground Color',
    background: 'Background Color',
    margin: 'Include Margin',
    logo: 'Add Logo',
    bulk: 'Bulk Generator',
    bulkDesc: 'Upload a CSV file with values in the first column.',
    csvUpload: 'Upload CSV',
    privacyNote: 'Privacy Friendly: All generation happens in your browser.',
    copied: 'Copied to clipboard!',
    error: 'An error occurred.',
    backToApp: 'Back to Generator',
    privacyPolicy: 'Privacy Policy',
    termsOfService: 'Terms of Service',
  },
  es: {
    title: 'QR Pro',
    subtitle: 'Estudio Profesional de Códigos QR',
    url: 'URL',
    text: 'Texto',
    whatsapp: 'WhatsApp',
    email: 'Correo',
    wifi: 'Wi-Fi',
    generate: 'Generar Código QR',
    downloadPng: 'Descargar PNG',
    downloadSvg: 'Descargar SVG',
    copy: 'Copiar al Portapapeles',
    size: 'Tamaño',
    color: 'Color de Frente',
    background: 'Color de Fondo',
    margin: 'Incluir Margen',
    logo: 'Añadir Logo',
    bulk: 'Generador Masivo',
    bulkDesc: 'Sube un archivo CSV con valores en la primera columna.',
    csvUpload: 'Subir CSV',
    privacyNote: 'Privacidad Protegida: Toda la generación ocurre en su navegador.',
    copied: '¡Copiado al portapapeles!',
    error: 'Ocurrió un error.',
    backToApp: 'Volver al Generador',
    privacyPolicy: 'Política de Privacidad',
    termsOfService: 'Términos de Servicio',
  },
  fr: {
    title: 'QR Pro',
    subtitle: 'Studio QR Code Professionnel',
    url: 'URL',
    text: 'Texte',
    whatsapp: 'WhatsApp',
    email: 'Email',
    wifi: 'Wi-Fi',
    generate: 'Générer le QR Code',
    downloadPng: 'Télécharger PNG',
    downloadSvg: 'Télécharger SVG',
    copy: 'Copier dans le Presse-papiers',
    size: 'Taille',
    color: 'Couleur de Premier Plan',
    background: 'Couleur de Fond',
    margin: 'Inclure la Marge',
    logo: 'Ajouter un Logo',
    bulk: 'Générateur en Masse',
    bulkDesc: 'Téléchargez un fichier CSV avec les valeurs dans la première colonne.',
    csvUpload: 'Télécharger CSV',
    privacyNote: 'Respect de la Vie Privée : Tout se passe dans votre navigateur.',
    copied: 'Copié dans le presse-papiers!',
    error: 'Une erreur est survenue.',
    backToApp: 'Retour au Générateur',
    privacyPolicy: 'Politique de Confidentialité',
    termsOfService: 'Conditions d\'Utilisation',
  },
  de: {
    title: 'QR Pro',
    subtitle: 'Professionelles QR-Code-Studio',
    url: 'URL',
    text: 'Text',
    whatsapp: 'WhatsApp',
    email: 'E-Mail',
    wifi: 'WLAN',
    generate: 'QR-Code generieren',
    downloadPng: 'PNG herunterladen',
    downloadSvg: 'SVG herunterladen',
    copy: 'In die Zwischenablage kopieren',
    size: 'Größe',
    color: 'Vordergrundfarbe',
    background: 'Hintergrundfarbe',
    margin: 'Rand hinzufügen',
    logo: 'Logo hinzufügen',
    bulk: 'Bulk-Generator',
    bulkDesc: 'Laden Sie eine CSV-Datei mit Werten in der ersten Spalte hoch.',
    csvUpload: 'CSV hochladen',
    privacyNote: 'Privatsphärenfreundlich: Alles wird in Ihrem Browser generiert.',
    copied: 'In die Zwischenablage kopiert!',
    error: 'Ein Fehler ist aufgetreten.',
    backToApp: 'Zurück zum Generator',
    privacyPolicy: 'Datenschutzrichtlinie',
    termsOfService: 'Nutzungsbedingungen',
  },
  pt: {
    title: 'QR Pro',
    subtitle: 'Estúdio Profissional de Códigos QR',
    url: 'URL',
    text: 'Texto',
    whatsapp: 'WhatsApp',
    email: 'E-mail',
    wifi: 'Wi-Fi',
    generate: 'Gerar QR Code',
    downloadPng: 'Baixar PNG',
    downloadSvg: 'Baixar SVG',
    copy: 'Copiar para Área de Transferência',
    size: 'Tamanho',
    color: 'Cor Principal',
    background: 'Cor de Fundo',
    margin: 'Incluir Margem',
    logo: 'Adicionar Logo',
    bulk: 'Gerador em Massa',
    bulkDesc: 'Carregue um arquivo CSV com valores na primeira coluna.',
    csvUpload: 'Carregar CSV',
    privacyNote: 'Privacidade Amigável: Toda a geração ocorre no seu navegador.',
    copied: 'Copiado para a área de transferência!',
    error: 'Ocorreu um erro.',
    backToApp: 'Voltar ao Gerador',
    privacyPolicy: 'Política de Privacidade',
    termsOfService: 'Termos de Serviço',
  }
};
